### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by 8Ozymandias** [xuopled/react-google-maps-loader#12]
Is this for just showing a regular static map or can it make use of features like Google Map Directions?

**Comment by xuopled** [comment]
This lib is just to load the `Google maps` SDK. 
To show a map, you can use my lib [react-google-map](https://github.com/xuopled/react-google-map) and to display an autocomplete input, you can use my other lib [react-google-places-suggest](https://github.com/xuopled/react-google-places-suggest)
