### ISSUE TITLE
Map Loading State as Render Prop

### ISSUE THREAD

**Issue by joshuaai** [xuopled/react-google-maps-loader#13]
Hello, thanks for this awesome library.

I load react-google-maps-loader lazily using a modal. For this use case, how can I access the map's loading state through the render props so that I can show a spinner while the map is loading?

This will be helpful, as I currently use the conditional rendering to show an error message if the map was not loaded successfully. Without the loading state, the error message pops up until the map is loaded.

**Comment by xuopled** [comment]
Hi @joshuaai , you should try this:

```
<ReactGoogleMapLoader
    params={{
        key: YOUR_API_KEY, // Define your api key here
        libraries: "places,geometry", // To request multiple libraries, separate them with a comma
    }}
    render={googleMaps =>
        googleMaps ? (
            <div>Google Maps is loaded !</div>
        ) : "loading"}
    />
```

**Comment by joshuaai** [comment]
Yeah, I want to use the conditional rendering that way, but to show both error and loading states.

I'm building primarily for users who don't have reliable internet so there'll be regular errors. So something like this:

```js
render=((googleMaps, loading) => 
  googleMaps ? <div>Google Maps is loaded !</div> 
  : 
  <div>
    { loading ? "isLoading..." : "Error loading maps. Please check your network." }
  </div>
)
```

**Comment by xuopled** [comment]
Ok I see, it could be a good idea but it will be a breaking change.

```
render=(({googleMaps, loading, errors}) =>  
  ...
)
```

⬆️ will be great.

Could you do a PR for this?

Thank you very much

**Comment by joshuaai** [comment]
#14  This provides the error state of the map to enable custom loading based on error types.

**Comment by xuopled** [comment]
I gave you some feedback
