### ISSUE TITLE
[BUG] You have included the Google Maps API multiple times

### ISSUE THREAD

**Issue by zomars** [xuopled/react-google-maps-loader#15]
With each remount, the loader is reinjecting the google maps script and this is appearing on the console:

```
You have included the Google Maps API multiple times on this page. This may cause unexpected errors.
```

**Comment by xuopled** [comment]
Hi @zomars, thenk you for reporting this, I will investigate about this

**Comment by xuopled** [comment]
I can't reproduce. Could you give me some details?
