### ISSUE TITLE
If loadGoogleMapSdk(params, callback) is called twice window.google becomes undefined

### ISSUE THREAD

**Issue by jjavierdguezas** [xuopled/react-google-maps-loader#18]
This is my first issue ever here in github, sorry if I do not follow the conventions. Also forgive my english.

For some reason in my code the  `loadGoogleMapsSdk(params, callback)` function is being called twice and because of that in the second call ` window.google = undefined;`

![image](https://user-images.githubusercontent.com/13673443/41550646-b50fc558-7329-11e8-859c-9f77dcec8178.png)

Because of that, I am receiving the following errors (and everything google-maps related stop working)

![image](https://user-images.githubusercontent.com/13673443/41550735-0c98bb36-732a-11e8-8297-6a989e7a7f2a.png)

When I comment that line, everything works fine

![image](https://user-images.githubusercontent.com/13673443/41550602-970131a0-7329-11e8-8333-3d8305fd7287.png)

So, should that line be removed or should I prevent that `loadGoogleMapsSdk` function from being called more than once?

[Also `state === LOADED` is `true` the second time ]

thanks in advance

**Comment by xuopled** [comment]
Hi @jjavierdguezas. I published a fix. Could you try the new 4.2.3 version ?

Thank you

**Comment by jjavierdguezas** [comment]
Thanks @xuopled , it works OK now.
