### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by cristiandley** [xuopled/react-google-maps-loader#2]
Hi,

im getting Unexpected Token at:

`@googleMapsLoader({ key: GOOGLE_MAPS_API_KEY, libraries: ['places','geometry'] })`

Could it be a webpack misconfiguration or something else im missing ?

Thanks

**Comment by xuopled** [comment]
Hi @cristiandley, sorry for the delay. I just published a `2.0.0` version. Could you check if that solve your problem ?

**Comment by xuopled** [comment]
I can't reproduce.
