### ISSUE TITLE
There is a problem with test on github

### ISSUE THREAD

**Issue by asaduryan** [xuopled/react-google-maps-loader#3]
npm ERR! peerinvalid Peer react-google-maps-loader@2.0.1 wants react@~15.3.0

can you change package.json react module version from ~15.3.0 to ~15.4.1, or help me?

**Comment by xuopled** [comment]
Hi, I will do that

**Comment by asaduryan** [comment]
thanx

**Comment by sseppola** [comment]
Hi, this is breaking my install process, do you have a chance to publish a new version?

**Comment by xuopled** [comment]
Just published it. Checkout the v2.0.2
